{
 "title": "Finnhub RealTime Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1000ms",
 "templating": {
  "list": [
   {
    "name": "ticker",
    "label": "Crypto Ticker",
    "query": {
     "query": "SELECT DISTINCT symbol FROM crypto_market_ksp. Trades;"
    }
   }
  ]
 },
 "panels": [
  { "title": "Crypto Price", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ticker" },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "select symbol, price, trade_timestamp from trades where symbol = '$ticker' and trade_timestamp>$__timeFrom and trade_timestamp<$__timeTo;\n\n"
    }
   ]
  },
  {
   "title": "Volume-Weighted Average Price from last 15 seconds",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "target": "SELECT ingest_timestamp AS \"time\", price_volume_multiply AS \"price_volume\" FROM running_averages_15_sec WHERE symbol = '$ticker' AND ingest_timestamp > $__timeFrom AND ingest_timestamp < $__timeTo;"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "target": "select symbol, volume, trade_timestamp from trades where symbol = '$ticker' and trade_timestamp>$__timeFrom and trade_timestamp<$__timeTo;"
    }
   ]
  }
 ]
}